### ISSUE TITLE
Not working in OC8

### ISSUE THREAD

**Issue by fxshpac** [eotryx/oc_files_mv#17]
Tried to install the app in OC8 but unfortunately it's not working. The Files view shows blank and frozen when the app is enabled. Just to report the issue here hoping @eotryx  can do something about it. Missed the app a lot since I have to file copying quite often in web interface. Thx in advance.

**Comment by franciscoluiz** [comment]
i confirm this. occours with me too

**Comment by oparoz** [comment]
Tracking...

**Comment by eotryx** [comment]
Initially fixed to work with OC8.
I need to write the unit tests now and the translation is currently not working as OC changed the translation behaviour.
